---
title: "P4DA_Ch4"
jupyter: python3
format: html
---

# Python 4 Data Analysis, Chapter 4 Notes

*Python for Data Analysis: Data Wrangling with pandas, NumPy & Jupyter* (3E), By Wes McKinney

## NumPy Basics

NumPy's importance comes from its array objects among other mathematical and C API capabilities.

Why NumPy is designed with efficiency with large data:

- NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. They also use much less memory.

- Can perform complex computations on entire arrays without `for` loops. NumPy is faster than regular Python because of its C-based algorithms that avoid overhead, extra memory or CPU cost that isn't going towards storing or processing data.

  NumPy can be 10-100 times faster (%timeit in IPy, timeit in Py)

```{python}
import numpy as np
#intro to ndarrays, shape(size of demensions) and dtype(data type descrip)
data = np.array([[1,2,0.3], [0,-3, 0.5]])
print(data*10)
print(data.shape, data.dtype)

```

## NumPy ndarray

Viable ndarray data can be a list and a list of equal length lists(2 in ex). Giving a shape of (1, elements) and (2, elements) respectively. NumPy infers shape from data so ndim and shape attributes can be used to check. You can use np.zeros, np.ones, and np.empty to create new arrays with all 0's, 1's or uninitialized memory(not all zeros, so only use to populate with new data. Pass tuples to make multidimensional.

```{python}
np.zeros(5)
np.ones((3,5))
np.empty((2,3,2))
#also
print(" ")
np.arange(17)
test_arr = np.asarray([[1,2,3,4], [4,3,2,1]])
test_one = np.ones_like(test_arr)
test_full = np.full_like(test_arr,10)
test_arr, test_one, test_full

np.eye(3)
np.identity(3)
```

Other useful NumPy array creations:

asarray- convert input to ndarray, but do not copy if the input is already an ndarray

arange- like range but returns an ndarray instead of a list

full- create array of the given shape and dtype with all values set to the indicated fill value

ones_like/also zeros, empty, full - takes another array and produces a (ones/zeros/etc)\_like array of the shape and data type

eye, identity - create a square N x N identity matrix (1s on the diagonal and 0s elsewhere)

### Data Types

This storage stratgy helps NumPy be so efficient with memory. There's a table of different types with the bit size category (int8). More important, here are the types of data int, float, complex(represented by 2 of the 32, 64 or 128 float options), bool (T/F), object(any Py object), string\_ and unicode\_ . Note Int has signed (can be negative) and unsigned(non-negative) and for 8bit signed is -128 to 127 while unsign is 0 to 255. (2\^8 = 256).

You can cast an array from one data type to another with `test_arr.astype(np.int32)` . If float to int it will truncate decimal and not round, can also apply to strings but apparently `np.string_`is a fixed size and might truncate without warning, pandas is better for that. astype always creates a new array (copy) even if that data is the same as the older version

### Arithmetic

You can do operations without for loops, perform arithmetic with a scalar on and arith between any equal size array. Comparisons will give a Boolean response.

```{python}
test_arr = np.asarray([[1,2,3,4], [4,3,2,1]])
10 * test_arr
test2 = np.array([[0,3,2,4], [0,3,3,-4]])
test_arr > test2
```

### Basic Indexing and Slicing

```{python}
#One Dimensional
arr = np.arange(10)
arr[5:8]
arr[5:8] = 12
arr
#12 is propogated/broadcast to [5:8]
arr_slice = arr[5:8]
arr_slice
arr_slice[1] = 12345
arr
#bare slice that assigns to all values in an array
arr_slice[:] = 73
arr
#Multidimensional
testnarr = np.array([[1,2,3],[4,5,6], [7,8,9]])
testnarr[1,1]
testnarr[1][1]
#slicing
tnar = testnarr
#1&2, 0&1
tnar[1:,:2]
#0, last element
tnar[:1,2:]
#[Start at:stop before]

```

Note: that array slices are views on the original array, so the data is not copied and any modifications to the view will be reflected in the source array. If you want a copy you can use `arr[5:8].copy()` Pandas does this too

### Boolean Indexing

You can create a boolean array to apply all where "Bob" in names to a different array to get those values in the same positions.

```{python}
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

data[names == "Bob"]
#ways to negate
#names != "Bob"
#~(names == "bob")
data[~(names == "Bob")]
#note you can also use ~ on a variable
# Can use &(and) and |(or), but only the symbols not keywords like Py
#based on how this works you can change all negative values to 0s 
data[data < 0] = 0
boop = np.arange(20).reshape((5,4))
boop
```

### Fancy Index

You can pass a list or ndarray of integers and get back those rows, this also works with negative indices. Also you can do `np.arange(20).reshape((5,4))` and create a 5,4 counting up to 20. Note that this copies the data into a new array when assigning the RESULT to a variable. If you assign values with fancy indexing, the values will be modified. Ex, `data[[index tuple]]` is copied, `data[[index tuple]] = 0` means modified list.

### Transposing Arrays and Swapping Axes

`.transpose` or `.T` allow you to transpose the matrix 3x5 to be 5x3. The example uses `np.dot(arr.T,arr`) to find the inner matrix product of the given array and it's transposition. `swapaxes` takes a pair of axis numbers and switches the indicated axes to rearrange the data, and is also a copy.

# Pseudorandom Number Generation

`np.random` adds to the built-in module `random` with arrays of sample values from different probability distributions like numpy.random.standard_normal . This is not random but instead generated by a configurable random number generator that deterministically determines what values are created. You can add seeds to start the rng in a particular place such as `rng = np.random.default_rng(seed=73737)` There are several methods that use the random number generator such as `permutation`, `shuffle`, `uniform`, `integers` and ones that give values within probability distributions, such as `standard_normal`, `binomial`, `normal`, `beta`, `chisquare`, and `gamma`.

# Universal Functions: Fast Element-Wise Array Functions

Universal function, ufunc, is a funtction that performs element-wise operations on data in ndarrays. Many are simple element-wise transformations like np.sqrt or np.exp (exponential). ufuncs that accept 1 array are unary ufuncs and ones that accept 2 arrays are binary, like np.add or np.maximum. Ufuncs accept an optional out arg that allows them to assign their results into an existing array instead of creating new. There are a lot of normal math/Comp Sci functions but some notable are **(unary)** sign(returning pos, 0, neg), rint (round elements to nearest integer), isnan (Boolean if not a number)

# Array-Oriented Programming with Arrays

`np.where` is a vectorized version of the ternary expression `x if condition else y` . You can combine scalar and/or arrays together.

```{python}
xarr = np.array([1,0,-2,-5,9,-1.5])

#np.where(condition, if then this, else this)
result = np.where(xarr >= 0, xarr, abs(xarr))
result
```

## Math and Stat Methods

```{python}
test = np.random.default_rng().standard_normal((7,3))
#can use array method or top-level Numpy function
test.mean()
np.mean(test)
# Functions like mean and sum take opt axis args
#sum by col
test.sum(axis=1)
#sum by rows
test.sum(axis=0)
```

NOTE you can use `sum()` for Boolean values as `True` is coerced to 1 etc.

### Other set Logic

`np.unique()`

`np.in1d(array, [values])` will return an array with Boolean values

# Files with Arrays

`np.save` and `np.load` . Arrays are saved in an uncompressed raw binary format with '.npy' extensions.

You can save multiple arrays in an uncompressed archive with np.savez like

```{python}
np.savez("array_arch.npz", a=arr1, b=arr2)

arch = np.load("array_arch.npz")

arch["b"]

#If it works well with data, you can compress like
np.savez_compressed("arrays_compressed.npz", a=arr1, a=arr2)
```
